services:
  rediscaching:
    image: rediscaching
    environment:
      redis: redisdata:6379
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redisdata
    ports:
      - 5153:8080
  redisdata:
    image: redis:latest
    volumes:
      - local-data:/data
    ports:
      - 6379:6379

volumes:
  local-data: 